[package]
name = "mira"
default-run = "mira"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/mira_plugin", "crates/mira_derive", "crates/mira_ui", "plugins/wave", "plugins/scoreboard"]

[dependencies]
mira_plugin = { path = "crates/mira_plugin" }
mira_derive = { path = "crates/mira_derive" }
libloading = "0.8"
anyhow = "1"
bytemuck = { version = "1.13", features = ["derive"] }
env_logger = "0.11"
glam = { version = "0.30", features = ["bytemuck"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "hdr"] }
gltf = { version = "1", default-features = false, features = ["import", "utils", "names", "KHR_materials_emissive_strength", "KHR_texture_transform"] }
half = { version = "2", features = ["bytemuck"] }
log = "0.4"
pollster = "0.3"
wgpu = "30.0.1"
winit = "0.30.12"
